//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.01.19 at 03:23:41 AM ART 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://schemas.xmlsoap.org/soap/envelope/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.xmlsoap.schemas.soap.envelope;
